# Generated by Django 3.0.4 on 2020-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('month', models.CharField(max_length=20)),
                ('text_report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('view', models.CharField(max_length=40)),
            ],
        ),
    ]
