# Generated by Django 3.0.4 on 2020-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_b',
            fields=[
                ('REGN', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('OKATO', models.CharField(default='0', max_length=2, null=True)),
                ('OKPO', models.CharField(default='0', max_length=8, null=True)),
                ('OGRN', models.CharField(default='0', max_length=13, null=True)),
                ('REGN_S', models.CharField(default='0', max_length=10, null=True)),
                ('BIC', models.CharField(default='0', max_length=9, null=True)),
                ('DT', models.CharField(default='0', max_length=10, null=True)),
                ('NAME_B', models.CharField(default='0', max_length=60, null=True)),
                ('ADR', models.CharField(default='0', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank_d',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('REGN', models.CharField(default='0', max_length=10, null=True)),
                ('C1', models.CharField(default='0', max_length=30, null=True)),
                ('C3', models.CharField(default='0', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank_s',
            fields=[
                ('REGN', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('C1_S', models.CharField(default='0', max_length=20, null=True)),
                ('C2_S', models.CharField(default='0', max_length=20, null=True)),
                ('C31_S', models.CharField(default='0', max_length=20, null=True)),
                ('C32_S', models.CharField(default='0', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=10)),
            ],
        ),
    ]
