# Generated by Django 3.0.4 on 2020-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_d',
            name='id',
        ),
        migrations.AlterField(
            model_name='bank_d',
            name='C1',
            field=models.CharField(default='0', max_length=30, primary_key=True, serialize=False),
        ),
    ]
