# Generated by Django 3.0.4 on 2020-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_auto_20200522_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_d',
            name='C1',
        ),
        migrations.RemoveField(
            model_name='bank_d',
            name='REGN',
        ),
        migrations.AddField(
            model_name='bank_d',
            name='REGN_C1',
            field=models.CharField(default='0', max_length=40, primary_key=True, serialize=False),
        ),
    ]
