# Generated by Django 3.0.4 on 2020-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_auto_20200522_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_n',
            fields=[
                ('C1', models.CharField(default='0', max_length=11, primary_key=True, serialize=False)),
                ('C2_1', models.CharField(default='0', max_length=130, null=True)),
                ('C2_2', models.CharField(default='0', max_length=80, null=True)),
                ('C2_3', models.CharField(default='0', max_length=50, null=True)),
            ],
        ),
    ]
