# Generated by Django 3.0.4 on 2020-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_delete_bank_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
