# Generated by Django 3.0.4 on 2020-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_bank_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_n',
            name='C2_1',
            field=models.CharField(default='0', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='bank_n',
            name='C2_2',
            field=models.CharField(default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bank_n',
            name='C2_3',
            field=models.CharField(default='0', max_length=70, null=True),
        ),
    ]
