# Generated by Django 3.0.4 on 2020-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_auto_20200523_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_n',
            name='C2_1',
            field=models.CharField(default='0', max_length=350, null=True),
        ),
    ]
