# Generated by Django 3.0.4 on 2020-05-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_bank_s'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_b',
        ),
    ]
