# Generated by Django 3.0.4 on 2020-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_delete_bank_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKATO', models.CharField(max_length=2)),
                ('OKPO', models.CharField(max_length=8)),
                ('OGRN', models.CharField(max_length=13)),
                ('REGN_S', models.CharField(max_length=3)),
                ('BIC', models.CharField(max_length=9)),
                ('NAME_B', models.CharField(max_length=60)),
                ('ADR', models.CharField(max_length=130)),
            ],
        ),
    ]
