# Generated by Django 3.0.4 on 2020-05-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_bank_b'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank_s',
            new_name='bank_SS',
        ),
    ]
