# Generated by Django 3.0.4 on 2020-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_auto_20200519_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='bank_SS',
            new_name='bank_s',
        ),
    ]
