# Generated by Django 3.0.4 on 2020-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0009_auto_20200519_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_s',
            name='C1_S',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='bank_s',
            name='C2_S',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='bank_s',
            name='C31_S',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='bank_s',
            name='C32_S',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='banks',
            name='name',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
