# Generated by Django 3.0.4 on 2020-06-06 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0010_froms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='froms',
            new_name='forms',
        ),
    ]
