# Generated by Django 3.0.4 on 2020-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0011_auto_20200606_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(default='none', max_length=110),
        ),
    ]
