# Generated by Django 3.0.4 on 2020-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0013_auto_20200607_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='forms',
            name='data',
            field=models.CharField(default='None', max_length=40, null=True),
        ),
    ]
