# Generated by Django 3.0.4 on 2020-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0014_auto_20200607_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='id',
        ),
        migrations.AddField(
            model_name='banks',
            name='REGN',
            field=models.CharField(default='None', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
