# Generated by Django 3.0.4 on 2020-06-10 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0015_auto_20200610_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='banks',
        ),
    ]
