# Generated by Django 3.0.4 on 2020-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Bank', '0016_delete_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('REGN', models.CharField(default='None', max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=60)),
            ],
        ),
    ]
